name: Jade-Mainframe

settings:
    DEVELOPMENT_TEAM: HQJF9G685U

options:
    bundleIdPrefix: wonder-team
    deploymentTarget:
        iOS: 14.0

targets:
    Jade-Mainframe:
        type: application
        platform: iOS
        settings:
            CODE_SIGN_ENTITLEMENTS: Jade-Mainframe/Jade-Mainframe.entitlements
        sources:
            - path: Jade-Mainframe
        scheme:
            testTargets:
                - Jade-MainframeTests
        preBuildScripts:
            - name: SwiftLint
              script: |
                "${PODS_ROOT}/SwiftLint/swiftlint"
            - name : SwiftGen
              script: |
                "${PODS_ROOT}/SwiftGen/bin/swiftgen"

    Jade-MainframeTests:
        type: bundle.unit-test
        platform: iOS
        sources:
            - path: Jade-MainframeTests



