name: CI

on: 
    push:
        branches:
            - master
            - development
            - dev/github-actions
    pull_request:
        branches:
            - master
            - development
jobs:
    Build:
        runs-on: macos-11
        steps:
            - uses: actions/checkout@v1

            - name: List available Xcode versions
              run: ls /Applications | grep Xcode

            - name: Select Xcode
              run: sudo xcode-select -switch /Applications/Xcode_12.5.app && /usr/bin/xcodebuild -version

            - name: Install pods
              run: pod install

            - name: Run unit tests
              run: xcodebuild -workspace Jade-Mainframe.xcworkspace -scheme Jade-Mainframe -destination platform\=iOS\ Simulator,OS\=14.5,name\=iPhone\ 12 build test | xcpretty && exit ${PIPESTATUS[0]}
